
  <div class="hero-unit">
    <h1>About Speckcommerce</h1>
    <p>Speckcommerce it's not Magento. </p>
    <p><a class="btn btn-primary btn-large" href="https://github.com/speckcommerce/speck">Fork SpeckCommerce on GitHub &raquo;</a></p>
  </div>
  <div class="row">
    <div class="span4">
      <h2>Evan Coury</h2>
        <p>Evan Coury is a web enthusiast and has experience in PHP since 2002. Evan Coury is an active contributor of ZF2 plus he is the one behind the Zend Framework revolution. Zend Framework which we see today as ZF2 is becuase of Evan Coury contribution to module manager.</p>
      <p><a class="btn btn-primary" href="http://framework.zend.com/zf2">ZF2 Development Portal &raquo;</a></p>

    </div>
    <div class="span4">
      <h2>Aleksey Khudyakov</h2>
       <p>Alesksey Khudyakov is also a web enthusiast with experience since 2004.</p>
      <p><a class="btn btn-primary" href="http://modules.zendframework.com/">Explore ZF2 Modules &raquo;</a></p>
   </div>
   <div class="span4">

     <h2>Nigel Lundsten</h2>
     <p>Nigel Lundsten is also a web enthusiast and working on speck from the begining.</p>
   </div>
  </div>