
  <div class="hero-unit">
    <h1>Our Mission</h1>
    <p>Speckcommerce it's not Magento. </p>
    <p><a class="btn btn-primary btn-large" href="https://github.com/speckcommerce/speck">Fork SpeckCommerce on GitHub &raquo;</a></p>
  </div>
  <div class="row">
    <div class="span4">
      <h2>Left Nav</h2>
        <p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. </p>
      <p><a class="btn btn-primary" href="http://framework.zend.com/zf2">ZF2 Development Portal &raquo;</a></p>

    </div>
    <div class="span8">
      <h2>Our Mission</h2>
       <p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. </p>
      <p><a class="btn btn-primary" href="http://modules.zendframework.com/">Explore ZF2 Modules &raquo;</a></p>
   </div>
   
  </div>